import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/footer/Footer";
import styled from "styled-components";

const Container = styled.div`
  height: 93vh;
  background: grey;
  background-image: url(../../public/assets/home/background-home-desktop.jpg);
`;

const Title = styled.div`
  font-family: 'Barlow Condensed';
  font-style: normal;
  font-weight: 400;
  font-size: 28px;
  line-height: 34px;
  letter-spacing: 4.725px;
  color: #D0D6F9;

  @media (max-width: 768px) {
    font-family: 'Barlow Condensed';
    font-style: normal;
    font-weight: 400;
    font-size: 16px;
    line-height: 19px;
    text-align: center;
    letter-spacing: 2.7px;
    color: #D0D6F9;
  }
`;

const Subtitle = styled.div`
  font-family: 'Barlow';
  font-style: normal;
  font-weight: 400;
  font-size: 18px;
  line-height: 32px;
  width: 500px;
  margin: 10px;
  color: #D0D6F9;

  @media (max-width: 768px) {
    font-family: 'Barlow';
    font-style: normal;
    font-weight: 400;
    font-size: 18px;
    line-height: 25px;
    width: 350px;
    text-align: center;
    margin: 20px;
    color: #D0D6F9;
  }
`;

const BigTitle = styled.div`
  font-family: 'Bellefair';
  font-style: normal;
  font-weight: 400;
  font-size: 150px;
  line-height: 172px;
  color: #FFFFFF;
  
  @media (max-width: 768px) {
    font-family: 'Bellefair';
    font-style: normal;
    font-weight: 400;
    font-size: 80px;
    line-height: 100px;
    text-align: center;
    color: #FFFFFF;
  }
`;

const TextWrapper = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  margin-left: 170px;
  padding-top: 240px;

  @media (max-width: 768px) {
    display: flex;
    flex-direction: column;
    justify-content: center;
    margin-left: 0px;
    padding-top: 20px;
    align-items: center;
    padding-top: 50px;
  }
`;

const Home: NextPage = () => {
  return (
    <>
      <Container>
        <Head>
          <title>Space Tourism</title>
          <meta name="description" content="Generated by create next app" />
          {/* <link rel="icon" href="/favicon.ico" /> */}
        </Head>

        <TextWrapper>
          <Title>SO, YOU WANT TO TRAVEL TO</Title>
          <BigTitle>Space</BigTitle>

          <Subtitle>
            Let’s face it; if you want to go to space, you might as well
            genuinely go to outer space and not hover kind of on the edge of it.
            Well sit back, and relax because we’ll give you a truly out of this
            world experience!
          </Subtitle>
        </TextWrapper>
      </Container>
      <Footer />
    </>
  );
};

export default Home;
