import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer } from '../components/footer/Footer'
import styled from 'styled-components';

const Container = styled.div`
  width: '100%';
  height: '100%';
  background-color: #fafafa;
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>🪐Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1>
          Space tourism
        </h1>
      </main>

      <Footer />
    </Container>
  )
}

export default Home
